[package]
name = "fse-trab-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bme280 = "0.5.1"
linux-embedded-hal = "0.4.0"
rppal = "0.18.0"
